package mocks

import (
	"kyaho-space/pkg/entities"

	"github.com/stretchr/testify/mock"
)

// MockMeetPlanRepository is an autogenerated mock type for the Repository type
type MockMeetPlanRepository struct {
	mock.Mock
}

func (m *MockMeetPlanRepository) CreateMeetPlan(meetPlan *entities.MeetPlan) error {
	args := m.Called(meetPlan)
	return args.Error(0)
}

func (m *MockMeetPlanRepository) ListMeetPlans() ([]entities.MeetPlan, error) {
	args := m.Called()
	if args.Get(0) != nil {
		return args.Get(0).([]entities.MeetPlan), args.Error(1)
	}
	return nil, args.Error(1)
}

func (m *MockMeetPlanRepository) DeleteMeetPlan(id string) error {
	args := m.Called(id)
	return args.Error(0)
}

// MockMeetPlanService is an autogenerated mock type for the Service type
type MockMeetPlanService struct {
	mock.Mock
}

func (m *MockMeetPlanService) AddMeetPlan(meetPlan *entities.MeetPlan) error {
	args := m.Called(meetPlan)
	return args.Error(0)
}

func (m *MockMeetPlanService) GetMeetPlans() ([]entities.MeetPlan, error) {
	args := m.Called()
	if args.Get(0) != nil {
		return args.Get(0).([]entities.MeetPlan), args.Error(1)
	}
	return nil, args.Error(1)
}

func (m *MockMeetPlanService) DeleteMeetPlan(id string) error {
	args := m.Called(id)
	return args.Error(0)
}
