package mocks

import (
	"kyaho-space/pkg/common"
	"kyaho-space/pkg/entities"

	"github.com/stretchr/testify/mock"
)

// MockWishlistRepository is an autogenerated mock type for the Repository type
type MockWishlistRepository struct {
	mock.Mock
}

func (m *MockWishlistRepository) CreateWishlist(wishlist *entities.Wishlist) error {
	args := m.Called(wishlist)
	return args.Error(0)
}

func (m *MockWishlistRepository) ListWishlists(params common.ListParams, year string) ([]entities.Wishlist, int64, error) {
	args := m.Called(params, year)
	if args.Get(0) != nil {
		return args.Get(0).([]entities.Wishlist), args.Get(1).(int64), args.Error(2)
	}
	return nil, args.Get(1).(int64), args.Error(2)
}

func (m *MockWishlistRepository) GetWishlistByID(id string) (*entities.Wishlist, error) {
	args := m.Called(id)
	if args.Get(0) != nil {
		return args.Get(0).(*entities.Wishlist), args.Error(1)
	}
	return nil, args.Error(1)
}

func (m *MockWishlistRepository) UpdateWishlist(wishlist *entities.Wishlist, updates map[string]interface{}) error {
	args := m.Called(wishlist, updates)
	return args.Error(0)
}

func (m *MockWishlistRepository) DeleteWishlist(id string) error {
	args := m.Called(id)
	return args.Error(0)
}

func (m *MockWishlistRepository) GetMaxPosition() (int, error) {
	args := m.Called()
	return args.Int(0), args.Error(1)
}

// MockWishlistService is an autogenerated mock type for the Service type
type MockWishlistService struct {
	mock.Mock
}

func (m *MockWishlistService) AddWishlist(wishlist *entities.Wishlist) error {
	args := m.Called(wishlist)
	return args.Error(0)
}

func (m *MockWishlistService) GetWishlists(params common.ListParams, year string) ([]entities.Wishlist, int64, error) {
	args := m.Called(params, year)
	if args.Get(0) != nil {
		return args.Get(0).([]entities.Wishlist), args.Get(1).(int64), args.Error(2)
	}
	return nil, args.Get(1).(int64), args.Error(2)
}

func (m *MockWishlistService) GetWishlistByID(id string) (*entities.Wishlist, error) {
	args := m.Called(id)
	if args.Get(0) != nil {
		return args.Get(0).(*entities.Wishlist), args.Error(1)
	}
	return nil, args.Error(1)
}

func (m *MockWishlistService) UpdateWishlist(wishlist *entities.Wishlist, updates map[string]interface{}) error {
	args := m.Called(wishlist, updates)
	return args.Error(0)
}

func (m *MockWishlistService) DeleteWishlist(id string) error {
	args := m.Called(id)
	return args.Error(0)
}
